
# Netlify configuration file

# This redirect rule tells Netlify to serve the index.html for any path
[build]
  publish = "dist"  # The folder to publish (output of your build)

# The following redirect rule ensures that all routes are handled by index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
